/* eslint-disable no-var */
/**
 * @see https://developer.ones.cn/docs/guide/advanced/storage
 * @summary ones.d.ts is generated by `op format` cli commands.
 * DO NOT MODIFY MANUALLY
 */
declare var ONESEntities: {
    dcp_base_config: {
        attributes: {
            key?: string;
            value?: string;
        };
        indexes: null;
    };
    dcp_phase_template: {
        attributes: {
            phase_code?: string;
            phase_name?: string;
            resolution_options?: string;
            resolution_template?: string;
            sort_order?: number;
            review_type?: string;
            dependencies?: string;
        };
        indexes: null;
    };
    dcp_material_template: {
        attributes: {
            material_name?: string;
            applicable_phases?: string;
            required?: boolean;
            responsible_role?: string;
            sort_order?: number;
            review_type?: string;
        };
        indexes: null;
    };
    dcp_indicator_template: {
        attributes: {
            indicator_name?: string;
            applicable_phases?: string;
            unit?: string;
            threshold_type?: string;
            yellow_threshold?: number;
            red_threshold?: number;
            sort_order?: number;
            review_type?: string;
        };
        indexes: null;
    };
    dcp_reviewer_role: {
        attributes: {
            role_name?: string;
            must_vote?: boolean;
            has_veto?: boolean;
            sort_order?: number;
            review_type?: string;
        };
        indexes: null;
    };
    dcp_review: {
        attributes: {
            review_uuid?: string;
            project_uuid?: string;
            phase_code?: string;
            review_title?: string;
            meeting_time?: number;
            status?: string;
            creator_uuid?: string;
            created_at?: number;
            updated_at?: number;
            review_number?: string;
            reviewers_json?: string;
            checklist_json?: string;
            review_type?: string;
            review_state?: string;
            round_no?: number;
            round_state?: string;
            state_history_json?: string;
        };
        indexes: null;
    };
    dcp_review_material: {
        attributes: {
            review_uuid?: string;
            template_id?: string;
            submit_status?: string;
            notes?: string;
            file_name?: string;
            file_data?: string;
            file_size?: number;
            uploaded_at?: number;
            updated_by?: string;
            updated_at?: number;
        };
        indexes: null;
    };
    dcp_review_indicator: {
        attributes: {
            review_uuid?: string;
            template_id?: string;
            current_value?: number;
            notes?: string;
            risk_color?: string;
            updated_by?: string;
            updated_at?: number;
        };
        indexes: null;
    };
    dcp_review_reviewer: {
        attributes: {
            review_uuid?: string;
            reviewer_uuid?: string;
            role_name?: string;
            conclusion?: string;
            risk_level?: string;
            opinion_summary?: string;
            submitted_at?: number;
        };
        indexes: null;
    };
    dcp_linked_issue: {
        attributes: {
            review_uuid?: string;
            issue_uuid?: string;
            issue_number?: string;
            issue_title?: string;
            issue_type?: string;
            issue_status?: string;
            linked_by?: string;
            linked_by_name?: string;
            linked_at?: number;
        };
        indexes: null;
    };
    dcp_resolution: {
        attributes: {
            review_uuid?: string;
            resolution_result?: string;
            final_conclusion?: string;
            resolution_body?: string;
            generated_by?: string;
            generated_at?: number;
            condition_notes?: string;
            based_on_votes?: string;
            snapshot_number?: string;
            published_by?: string;
            published_by_name?: string;
            published_at?: number;
        };
        indexes: null;
    };
    dcp_supplement: {
        attributes: {
            review_uuid?: string;
            note_type?: string;
            note_title?: string;
            note_content?: string;
            submitted_by?: string;
            submitted_at?: number;
        };
        indexes: null;
    };
    dcp_audit_log: {
        attributes: {
            review_uuid?: string;
            timestamp?: number;
            operator_uuid?: string;
            action?: string;
            target?: string;
            detail?: string;
            result?: string;
        };
        indexes: null;
    };
    dcp_checklist_item: {
        attributes: {
            phase_code?: string;
            role_name?: string;
            item_text?: string;
            sort_order?: number;
            review_type?: string;
        };
        indexes: null;
    };
    dcp_checklist_result: {
        attributes: {
            review_uuid?: string;
            template_id?: string;
            status?: string;
            checked_by?: string;
            checked_at?: number;
        };
        indexes: null;
    };
};
